---
# ServiceMonitor for Prometheus Operator to scrape metrics
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: api-gateway
  namespace: api-gateway
  labels:
    app: api-gateway
    component: monitoring
    prometheus: kube-prometheus
spec:
  selector:
    matchLabels:
      app: api-gateway
      component: gateway

  namespaceSelector:
    matchNames:
      - api-gateway

  endpoints:
    - port: metrics
      interval: 30s
      path: /metrics
      scheme: http

      # Relabeling for better metric organization
      relabelings:
        - sourceLabels: [__meta_kubernetes_pod_name]
          targetLabel: pod
        - sourceLabels: [__meta_kubernetes_pod_node_name]
          targetLabel: node
        - sourceLabels: [__meta_kubernetes_namespace]
          targetLabel: namespace
        - sourceLabels: [__meta_kubernetes_service_name]
          targetLabel: service

      # Metric relabeling
      metricRelabelings:
        - sourceLabels: [__name__]
          regex: 'go_.*'
          action: drop  # Drop Go runtime metrics if not needed
        - sourceLabels: [__name__]
          regex: 'process_.*'
          action: drop  # Drop process metrics if not needed
